name: Archeon Monthly Build

on:
 # schedule:
 #   - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git archiso squashfs-tools

      - name: Run buildiso.sh
        run: |
          chmod +x ./buildiso.sh
          ./buildiso.sh

      - name: Set release info
        id: set_release
        run: |
          export TITLE="$(date +'%B %Y')"
          export TAG="$(date +'%B.%Y' | tr '[:upper:]' '[:lower:]')"
          echo "title=$TITLE" >> "$GITHUB_OUTPUT"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.set_release.outputs.title }}
          tag_name: ${{ steps.set_release.outputs.tag }}
          make_latest: true
          files: |
            out/desktop/*.iso
            out/desktop/*.sha256
